### ISSUE TITLE
Allow to set bot name

### ISSUE THREAD

**Issue by vterdunov** [adrey/slack-file-upload-action#13]
If it possible for files.upload slack method. please add an ability to set custom bot name.

**Comment by adrey** [comment]
Action uses internally this API method https://api.slack.com/methods/files.upload
It's not possible to specify bot name directly, but bot depends on `token`  specified in action parameters `token: ${{ secrets.SLACK_TOKEN }}`

**Comment by vterdunov** [comment]
Yeah. Weird API inconsistency. Anyway thanks for the quick answer and the slack-file-upload-action.
