### ISSUE TITLE
I'm getting invalid auth error 

### ISSUE THREAD

**Issue by david13Lopez** [adrey/slack-file-upload-action#14]
Hi, 

I have my code like it 

token: ${{ secrets.SLACK_TOKEN }} 
path: mochawesome-report/mochawesome.html
 channel: random

and it is giving me that error:

 with:
    token: ***
    path: mochawesome-report/mochawesome.html
  env:
    NPM_CONFIG_USERCONFIG: /runner-tmp/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
invalid_auth
Error: invalid_auth
invalid_auth
Error: invalid_auth

**Comment by adrey** [comment]
Hi!
```invalid_auth
Error: invalid_auth
```
This means that something wrong with your slack token

Check if some of the setup steps missed: https://github.com/adrey/slack-file-upload-action/blob/master/README.md
