### ISSUE TITLE
Error: missing_scope

### ISSUE THREAD

**Issue by aholovenko** [adrey/slack-file-upload-action#15]
Hi, I am getting this error while trying to upload file to slack:

```
Run adrey/slack-file-upload-action@master
  with:
    token: ***
    path: ./file.xlsx
    channel: XXXXXXXXXX
    initial_comment: XXXXXXXXXX
    title: ${XXXXXXXXXX}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.6.12/x64/lib
    XXXXXXXXXX: XXXXXXXXXX.xlsx
missing_scope
Error: missing_scope
missing_scope
Error: missing_scope
```

` runs-on: ubuntu-18.04`

Can you help fixing this issue?

**Comment by adrey** [comment]
Hi,
Did you get `file:write` permission to your token?
According this https://api.slack.com/methods/files.upload some permissions are missing

**Comment by aholovenko** [comment]
> Hi,
> Did you get `file:write` permission to your token?
> According this https://api.slack.com/methods/files.upload some permissions are missing

This helps! Thank you :)
