### ISSUE TITLE
Trying to upload file but "missing_scope"

### ISSUE THREAD

**Issue by vem-popprika** [adrey/slack-file-upload-action#28]
![image](https://user-images.githubusercontent.com/109714693/228154576-3f107c23-2a4e-4d58-80b3-1edf397fc072.png)

this error phrase has been occured when I'm trying to upload .apk file. 
am I missing something?

this is what I'm trying below.

- name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_OAUTH_TOKEN }}
        path: my_apk_path.apk
        channel: my_channel

**Comment by jesperrula** [comment]
+1

**Comment by jesperrula** [comment]
Ah! Figure it out. @vem-popprika you need to check that your token is correct (in Slack) and that it has the correct permissions. Don't mistake user and app tokens (like I did).

**Comment by vem-popprika** [comment]
@jesperrula 
Yes It surely was authorizing issue but I had no clue with that message. 
anyway, problem solved. thanks!
