### ISSUE TITLE
Can't upload file on slack 

### ISSUE THREAD

**Issue by radheyshyamjat** [adrey/slack-file-upload-action#4]
name: Android CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
 build:
   runs-on: ubuntu-latest
 
   steps:
     - name: "Action CheckOut"
       uses: actions/checkout@master
     - name: "Build Android project"
       uses: vgaidarji/android-github-actions-build@v1.0.1
       with:
         args: "./gradlew assembleDebug"
     - name: Upload APK
       uses: actions/upload-artifact@v2
       with:
          name: app
          path: app/build/outputs/apk/debug/*.apk
     - run: echo "Debug file " > debug.apk
     - name: "Upload file on Slack"
       uses: adrey/slack-file-upload-action@master
       with:
         token: "Slack Token"
         path: debug.apk
         channel: random

**Comment by adrey** [comment]
Hi! Check your configuration and provide build output of action.

> token: "Slack Token"
 You should replace this by real slack token https://slack.com/intl/en-ru/help/articles/215770388-Create-and-regenerate-API-tokens

**Comment by radheyjat** [comment]
Yes i am put token: YES I AM PUT HERE IS ACTUAL TOKEN BUT NOT WORKING

**Comment by adrey** [comment]
https://github.com/adrey/slack-upload-action-test - working example. You can try it wih your token. 
You also didn't provide your action build output
