### ISSUE TITLE
Slack sends error responses with status 200

### ISSUE THREAD

**Issue by msanatan** [adrey/slack-file-upload-action#5]
Hi @adrey, thanks for this Github action! It's really simple and clear.

I hooked it up today for a private project, added the `token` and tried to upload a file.  The action completed successfully, but  no files were uploaded. The code for this action is straightforward, I figured I should look at Slack's response body to see what was happening.

I changed the submit callback to this:

```javascript
form.submit("https://slack.com/api/files.upload", function (err, res) {
    console.log(res.statusCode);
    res.resume();

    res.on('data', function (chunk) {
        str += chunk;
    });

    res.on('end', function () {
        console.log(str);
    });
});
```

I created the `str` variable as a blank string earlier in the file to make it work. When running this module with that code I got the following output:

```plaintext
200
{"ok":false,"error":"not_in_channel"}
```

Even though we get a 200 response, Slack returns an error message.

Turns out I needed to invite my bot user to the channel. I never used Slack apps before, so I don't know all the integration steps - definitely not your fault. However, I'd like to propose these enhancements if that's OK:

1. Can we update the Readme to specify that it's the Bot Oauth2 Token? I'm new to Slack APIs and there are many things labeled tokens, it'll help beginners like me know where to go :-).
1. Can we specify the required setup for this to work? Again, it's probably obvious for you and others but I had no clue about having the right permissions and inviting the bot to the channel. It's not that we'd provide the steps, but having just mentioning them would point users to the right direction.
1. Can we check the response body for errors? A successful response has the `ok` property of the JSON set to `true`. We can first inspect that property, and if `false` we can log the error and ensure that the action fails. Removing false positives will be a better experience!

This weekend might be a bit packed for me, but I can make some time next week to look into it. Let me know if that's OK!

**Comment by adrey** [comment]
Hello @msanatan! Good point, should be done. I have some time this week, but if I won't able to finish it, I'll reassign this issue to you, OK?

**Comment by msanatan** [comment]
Thanks for checking in so quickly! That's more than fine with me, I'm happy to help code/test as required

**Comment by adrey** [comment]
Hi @msanatan! https://github.com/adrey/slack-file-upload-action/blob/master/README.md how do you think, would be that enough for enhancement 1. and 2.? For point 3 I didn't have time on weekend, so if you're interested - issue is yours. 
Here's guide for creation js action: https://help.github.com/en/actions/creating-actions/creating-a-javascript-action
You'll need `zeit/ncc` for compiling code into single file for distribution

**Comment by msanatan** [comment]
Thanks, that link suffices @adrey. If anything else comes to mind I'll add it. Regarding the code change, I'll have a look and submit a PR. Should have something by this week
